### ISSUE TITLE
There seems to be some problems with srp's experiments

### ISSUE THREAD

**Issue by Peng-weil** [SoftWiser-group/NeSy-without-Shortcuts#1]
Thank you for your elegant work! However, I have found some errors in the srp experiment. Specifically, on line 163 of "srp_exp/logic_training.py," it seems that you are trying to forward propagate the subgraph of the adjacency matrix (representing the connection between two nodes) into the previously defined GCN. However, generally speaking, the subgraph of two nodes is a 2x2 matrix, which cannot be fed into the fully connected layer defined for the entire graph previously. I'm not sure if my understanding is correct, but running your experiment did indeed result in an error. I look forward to your reply.

Thank you again for your hard work.

**Comment by Lizn-zn** [comment]
I apologize for the delayed response. I found that there is a bug in Line 90, which causes an improper row-column swap. I have fixed it, thanks!
